aba:
  industry:
    bus:
      director:
        location: industry-director
        protocol: tcp
        receivePort: 5558
        publishPort: 5559
      router:
          location: industry-router
          protocol: tcp
          port: 42001

logging:
  level:
    com.aba: DEBUG