spring:
  datasource:
    url: jdbc:mysql://host:port/database
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jmx:
    enabled: false
#logging:
#  level:
#    net.maurerit: DEBUG
server:
  tomcat:
    max-threads: 80